"""add_user_and_home_fields

Revision ID: 22f28043f2db
Revises: bd430250a6cb
Create Date: 2025-11-26 03:33:12.956419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22f28043f2db'
down_revision: Union[str, Sequence[str], None] = 'bd430250a6cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homes', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('homes', sa.Column('contact_number', sa.Text(), nullable=True))
    op.add_column('homes', sa.Column('home_size', sa.Text(), nullable=True))
    op.add_column('homes', sa.Column('number_of_rooms', sa.Integer(), nullable=True))
    op.add_column('homes', sa.Column('house_type', sa.Text(), nullable=True))
    op.add_column('homes', sa.Column('status', sa.String(length=50), nullable=False, server_default="New Home Registered"))
    op.add_column('users', sa.Column('first_name', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('contact_number', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('operational_area', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('experience_level', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('certifications', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'certifications')
    op.drop_column('users', 'experience_level')
    op.drop_column('users', 'operational_area')
    op.drop_column('users', 'contact_number')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('homes', 'status')
    op.drop_column('homes', 'house_type')
    op.drop_column('homes', 'number_of_rooms')
    op.drop_column('homes', 'home_size')
    op.drop_column('homes', 'contact_number')
    op.drop_column('homes', 'address')
    # ### end Alembic commands ###
